# Configuration defaults
# Settings are separated into hyperparameters for architecture, data, implementation and train/eval hyperparams
defaults:
  - arch: crammed-depthrecurrent
  - data: arithmetic
  - impl: torch-default
  - wandb: default
  - train: cramming
  - _self_
  - override hydra/job_logging: custom

base_dir: outputs
model_dir: ${base_dir}
data_dir:

hydra:
  sweep:
    dir: ${base_dir}/${name}/pretrain/${now:%Y-%m-%d}/${now:%H-%M-%S}
  run:
    dir: ${base_dir}/${name}/pretrain/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True

seed: # Optional: Set initial seed
name: default # A name for this run [will be used for the summary table and outputs folder]

# Total and central computation budget in hours:
budget: 4
overall_budget: ${budget}

# debug implementation by running every loop just once:
dryrun: False
